package com.dicoding.sayurtaniku.model

import com.dicoding.sayurtaniku.R

object FakeSayurDataSource {
    val dummySayurku = listOf(
        Sayur(1, R.drawable.sayur_1, "Sayur Bayam Hijau", 6000,"Sayur Bayam Hijau, yang juga dikenal sebagai bayam, adalah jenis sayuran yang dikenal karena daun-daunnya yang hijau, lembut, dan berguna secara nutrisi. Daun bayam ini biasanya memiliki bentuk oval atau hati dengan warna hijau yang cerah. Kelebihan sayur bayam hijau tidak hanya terletak pada rasa yang lezat, tetapi juga pada kandungan gizinya yang melimpah."),
        Sayur(2, R.drawable.sayur_2, "Brassica oleracea L.", 4500,"Brassica oleracea L. Var italica, yang lebih umum dikenal sebagai brokoli, adalah sayuran yang berasal dari keluarga kubis-kubisan (Brassicaceae) dan merupakan varietas dari tanaman kubis liar (Brassica oleracea). Brokoli memiliki penampilan yang khas dengan kepala bunga yang rapat dan tangkai yang panjang. Tanaman ini dikenal karena keberagaman manfaat kesehatannya dan telah menjadi salah satu sayuran yang populer di berbagai masakan di seluruh dunia."),
        Sayur(3, R.drawable.sayur_3, "Paprika Fresh", 5000,"Paprika adalah sayuran yang berasal dari genus Capsicum dalam keluarga Solanaceae. Tanaman ini dikenal karena buahnya yang beragam warna, mulai dari merah, hijau, kuning, hingga oranye. Paprika memiliki rasa yang manis atau pedas tergantung pada varietasnya. Buah paprika mengandung vitamin C, vitamin A, dan antioksidan, menjadikannya pilihan yang sehat dan lezat dalam berbagai masakan. Paprika dapat dikonsumsi segar, dimasak, atau digunakan sebagai bahan utama dalam saus, salad, atau hidangan lainnya."),
        Sayur(4, R.drawable.sayur_4, "Jagung Manis", 6000,"Jagung, atau Zea mays, adalah tanaman biji-bijian yang berasal dari Amerika. Tanaman ini dikenal dengan tongkolnya yang mengandung butiran-butiran jagung yang biasa disebut biji jagung. Biji jagung memiliki rasa manis dan kenyal, membuatnya menjadi salah satu sumber karbohidrat yang populer di seluruh dunia. Jagung sering dikonsumsi dalam berbagai bentuk, seperti jagung rebus, panggang, atau diolah menjadi produk makanan seperti tepung jagung, puding jagung, dan keripik jagung. Selain sebagai makanan manusia, jagung juga digunakan sebagai pakan ternak dan bahan baku industri. Tanaman jagung tumbuh subur di berbagai iklim dan sering dijadikan simbol musim panen yang melimpah."),
        Sayur(5, R.drawable.sayur_5, "Wortel", 2000,"Wortel adalah sayuran berakar yang terkenal dengan warna oranye cerahnya, meskipun ada juga varietas dengan warna ungu, kuning, atau merah. Tanaman ini termasuk dalam genus Daucus dan keluarga Apiaceae. Wortel memiliki akar yang panjang, silindris, dan renyah, serta daun hijau yang tumbuh di bagian atasnya. Kaya akan beta-karoten, wortel dikenal baik untuk kesehatan mata. Selain itu, wortel mengandung serat yang baik untuk pencernaan dan vitamin serta mineral penting, seperti vitamin K dan potasium. Wortel sering dikonsumsi segar, direbus, dipanggang, atau diolah menjadi jus, dan menjadi bahan dasar dalam banyak hidangan masakan."),
        Sayur(6, R.drawable.sayur_6, "Kacang Polong", 5000,"Kacang polong, juga dikenal sebagai kacang hijau atau pea, adalah jenis sayuran berbentuk biji yang termasuk dalam keluarga Fabaceae. Tanaman ini dihasilkan oleh tumbuhan Pisum sativum. Kacang polong memiliki ciri khas berbentuk bulat dan terbungkus dalam kelopak tipis yang disebut polong. Warna polong dapat bervariasi dari hijau hingga kuning tergantung pada varietasnya."),
        Sayur(7, R.drawable.sayur_7, "Cucumber", 8000,"Cucumber atau ketimun adalah sayuran segar yang tergolong dalam keluarga labu-labuan (Cucurbitaceae) dan memiliki karakteristik bentuk silinder yang panjang. Dikenal dengan kulitnya yang hijau, ketimun memiliki daging yang renyah dan banyak mengandung air. Rasanya ringan dan segar, menjadikannya pilihan populer dalam salad, acar, atau sebagai camilan yang menyegarkan. Ketimun juga rendah kalori dan mengandung beberapa nutrisi seperti vitamin K, vitamin C, dan kalium. Karena kandungan air yang tinggi, ketimun membantu menjaga tubuh terhidrasi dan memberikan sensasi kesegaran."),
        Sayur(8, R.drawable.sayur_8, "Green Chili", 10000,"Green chili, atau sering disebut cabai hijau, merujuk pada berbagai varietas cabai yang dipanen saat masih berwarna hijau dan belum mencapai kedewasaan penuh, di mana warnanya sering berubah menjadi merah, kuning, atau oranye, tergantung pada jenis cabainya. Cabai hijau umumnya digunakan sebagai bumbu untuk menambahkan rasa pedas dan aroma pada berbagai masakan."),
        Sayur(9, R.drawable.sayur_9, "Bawang Merah", 6000,"Bawang merah, atau red onion dalam bahasa Inggris, adalah jenis bawang yang dikenal karena warna kulitnya yang berwarna ungu kecokelatan. Bawang ini memiliki daging yang berwarna merah keunguan dan memiliki rasa yang lebih manis dan ringan dibandingkan dengan bawang bombay. Bawang merah sering digunakan sebagai bumbu dalam berbagai masakan untuk menambahkan cita rasa khasnya. Bawang merah dapat dikonsumsi baik dalam bentuk mentah maupun dimasak. Dalam keadaan mentah, bawang merah sering digunakan dalam salad, salsas, atau sebagai hiasan pada hidangan. Ketika dimasak, bawang merah dapat di tumis, digoreng, atau diolah menjadi bawang goreng sebagai pelengkap hidangan."),
        Sayur(10, R.drawable.sayur_10, "Kentang", 4000,"Kentang, atau potato dalam bahasa Inggris, adalah tanaman umbi yang ditanam untuk dikonsumsi biji umbinya. Kentang berasal dari Amerika Selatan dan merupakan salah satu sumber karbohidrat yang penting di banyak bagian dunia. Tanaman kentang dikenal dengan daun-daunnya yang besar dan umbinya yang berkembang di bawah tanah. Kentang memiliki tekstur yang lembut dan rasa yang netral, sehingga dapat diolah dalam berbagai cara. Kentang sering direbus, dipanggang, atau digoreng, dan dapat dijadikan berbagai hidangan, seperti kentang rebus, kentang tumbuk, kentang goreng, atau keripik kentang. Selain itu, kentang juga digunakan sebagai bahan dasar dalam pembuatan kue, roti, atau sup."),
        Sayur(11, R.drawable.sayur_11, "Bawang Putih", 2000,"Bawang putih, atau garlic dalam bahasa Inggris, adalah tanaman umbi yang digunakan sebagai bumbu dalam berbagai masakan di seluruh dunia. Bawang putih memiliki rasa tajam dan aroma yang khas, dan biasanya digunakan baik dalam bentuk mentah maupun dimasak. Tanaman ini memiliki umbi berbentuk cangkir yang terdiri dari beberapa yang dapat dipisahkan. Bawang putih sering digunakan untuk memberikan cita rasa khas pada hidangan seperti tumisan, sup, saus, dan berbagai hidangan lainnya. Bawang putih juga dikenal karena potensi manfaat kesehatannya, termasuk sifat antibakteri dan antioksidan. Oleh karena itu, bawang putih kadang-kadang digunakan dalam pengobatan tradisional untuk meningkatkan kesehatan."),
        Sayur(12, R.drawable.sayur_12, "Terong Fresh", 5000,"Terong, atau eggplant dalam bahasa Inggris, adalah tanaman buah-buahan yang berasal dari keluarga Solanaceae. Tanaman ini memiliki buah berbentuk oval atau silinder, dan warna buahnya dapat bervariasi dari ungu tua, ungu terang, hijau, hingga putih, tergantung pada jenis dan varietasnya.Buah terong memiliki daging yang lembut dan berbiji kecil di dalamnya. Terong sering digunakan dalam berbagai masakan di seluruh dunia, terutama di masakan Asia, Mediterania, dan Timur Tengah. Buahnya dapat dipanggang, digoreng, direbus, atau diolah menjadi saus atau tumisan. Terong juga dapat dijadikan bahan dasar dalam hidangan seperti ratatouille, caponata, atau curry terong."),
    )
}